[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"  # Changed from "frontend/dist" to just "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200